resources:
- name: example
  type: git
  source:
    uri: https://github.com/concourse/examples.git

- name: send-an-email
  type: email
  source:
    smtp:
      host: email-smtp.ap-south-1.amazonaws.com
      port: "587"
      username: AKIAUYSJT5EDJG5K4HEL
      password: BDrfKOERoQSteF21u6w3fcMaNBQXi5EEERYQV3DKr7NW
    from: rahulducat2019@gmail.com
    to: [ rahulducat2019@gmail.com ]


resource_types:
  - name: email
    type: docker-image
    source:
      repository: pcfseceng/email-resource


jobs:
- name: hello-job
  plan:
    - get: example
      trigger: true
    - task: hello_task
      config:
        platform: linux
        image_resource: {type: registry-image, source: {repository: bash}}
          
        inputs:
        - name: example
        run:
          path: bash
          args: 
          - -c
          - |
           cat example/README.md > read
        outputs:
        - name: email-out

    - put: send-an-email
      params:
        subject: "test"
        body: "test"
