resources:
- name: example
  type: git
  source:
    uri: https://github.com/concourse/examples.git


jobs:
- name: hello-job
  plan:
    - get: example
      trigger: true
    - task: hello_task
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: bash
        inputs:
        - name: example
        run:
          path: bash
          args: 
          - -c
          - |
           cat example/README.md