jobs:
- name: hello-job
  plan:
    - task: hello_task
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: busybox
        outputs:
        - name: artifacts
        run:
          path: ls
          args: ["-lF"]
        