jobs:
- name: hello-job
  plan:
    - task: hello_task
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: busybox
        outputs:
        - name: artifacts
        run:
          path: sh
          args: 
          - -cx
          - |
            ls -l
            echo "Hello from another step!" > artifacts/message
    # Addind second task that reads message from artifacts       
    - task: read-artifacts
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: busybox
        inputs:
        - name: artifacts
        run:
          path: sh
          args:
          - -cx
          - |
            ls -l
            cat artifacts/message
