resources:
- name: repo
  type: git
  source:
    uri: git@github.com:Rahul-Soni28/capstone.git
    branch: development
    private_key: |
      -----BEGIN OPENSSH PRIVATE KEY-----
      
      -----END OPENSSH PRIVATE KEY-----
- name: send-an-email
  type: email
  source:
    smtp:
      host: smtp.gmail.com
      port: "465"
      username: rahulducat2019@gmail.com
      password: vhgdgfgchg
    from: rahulducat2019@gmail.com
    to: [ rahulducat2019@gmail.com ]
- name: maven-image
  type: docker-image
  source:
    repository: maven
    tag: 3.6.0-jdk-8-alpine

resource_types:
  - name: email
    type: docker-image
    source:
      repository: pcfseceng/email-resource

jobs:
- name: prod
  plan:
    - get: maven-image
    - get: repo
      trigger: true
    - task: test
      image: maven-image
      config:
        platform: linux
        inputs: [name: repo]
        run:
          path: mvn
          args: ["clean test"]
          dir: repo
    - task: pack
      config:
        image_resource:
          type: docker-image
          source: 
            repository: maven 
            tag: 3.6.0-jdk-8-alpine
        platform: linux
        inputs: [name: repo]
        run:
          path: mvn
          args: ["package"]
          dir: repo
    - put: send-an-email
      params:
        subject: "email-out/generated-subject"
        body: "email-out/generated-body"
